model_list:
  - model_name: claude-opus-5
    litellm_params:
      model: bedrock/global.anthropic.claude-opus-5
  - model_name: claude-opus-4-6
    litellm_params:
      model: bedrock/global.anthropic.claude-opus-4-6-v1
  - model_name: claude-haiku-4-5
    litellm_params:
      model: bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0
      max_tokens: 8192
  - model_name: gpt-oss-120b
    litellm_params:
      model: bedrock/openai.gpt-oss-120b-1:0
      max_tokens: 8192

litellm_settings:
  drop_params: true
  cache: true
  cache_params:
    type: redis
    host: redis
    port: 6380