services:
  db:
    container_name: litellm-db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: your-postgres-username
      POSTGRES_PASSWORD: your-postgres-password
      POSTGRES_DB: litellm
    volumes:
      - litellm-bedrock-pg:/var/lib/postgresql/data
      
  redis:
    container_name: litellm-redis
    image: redis:7-alpine
    ports:
      - "6380:6380"
    volumes:
      - litellm-bedrock-redis:/data
    command: redis-server --appendonly yes --port 6380

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    ports:
      - "4000:4000"

    volumes:
      # LiteLLM config
      - ./config.yaml:/app/config.yaml

      # AWS credentials (required for Bedrock)
      - ~/.aws:/root/.aws:ro

    environment:
      AWS_REGION: your-aws-region
      AWS_PROFILE: your-aws-sso-profile
      DATABASE_URL: postgresql://your-postgres-username:your-postgres-password@db:5432/litellm
      LITELLM_MASTER_KEY: your-litellm-master-key
      REDIS_HOST: redis
      REDIS_PORT: "6380"

    depends_on:
      - db
      - redis

    command:
      - "--config"
      - "/app/config.yaml"

volumes:
  litellm-bedrock-redis:
    external: false
  litellm-bedrock-pg:
    external: true
